<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function cu_class_primer_bundle_menu() {
  $items['admin/config/system/class-primer'] = array(
    'title' => 'Class Primer',
    'description' =>  'Import classes.',
    'page callback' => 'cu_class_primer_import',
    'access arguments' => array('administer modules'),
  );

  $items['primer/courses'] = array(
    'title' => 'Class Primer - Master XML',
    'description' =>  'Import classes.',
    'page callback' => 'cu_class_primer_master',
    'access callback' => 'cu_class_primer_access',
    'type' => MENU_CALLBACK,
  );

  $items['primer/class'] = array(
    'title' => 'Class Primer - Detail XML',
    'description' =>  'Import classes.',
    'page callback' => 'cu_class_primer_detail',
    'access callback' => 'cu_class_primer_access',
    'type' => MENU_CALLBACK,
  );

  $items['primer/classes'] = array(
    'title' => 'Class Primer - Detail XML',
    'description' =>  'Import classes.',
    'page callback' => 'cu_classes_primer_detail',
    'access callback' => 'cu_class_primer_access',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Access callback for ??
 */
function cu_class_primer_access() {
  // switch to a custom permission?
  return TRUE;
}

/**
 * A basic course listing
 */
function cu_class_primer_master($arg2, $arg3, $arg4) {
  drupal_add_http_header('Content-Type', 'text/xml');
  //$inst = 'CUBLD';
  //$term = '2164';
  //$subject = 'HIST';

  $inst = $arg2;
  $term = $arg3;
  $subject = $arg4;

  $output = '<?xml version="1.0" encoding="UTF-8"?>
  <SSR_GET_CLASSES_RESP xmlns="http://xmlns.oracle.com/Enterprise/HCM/services">
    <SEARCH_RESULT>
      <SUBJECTS>';
  $results = db_query('SELECT * FROM {class_search} WHERE SBJCT_CD = :subject', array(':subject' => $subject));


  foreach ($results as $course) {
    //mimic XML structure from master response
    //dsm($course);
    $title = check_plain($course->CRSE_TTL_LD);
    $output .= "
    <SUBJECT>
      <CRSE_ID>$course->CRSE_CD</CRSE_ID>
      <SUBJECT>$course->SBJCT_CD</SUBJECT>
      <CATALOG_NBR>$course->CATALOG_NBR</CATALOG_NBR>
      <ACAD_CAREER>$course->ACAD_CAR_CD</ACAD_CAREER>
      <COURSE_TITLE_LONG>$title</COURSE_TITLE_LONG>
      <CRSE_OFFER_NBR>1</CRSE_OFFER_NBR>
    </SUBJECT>";
  }

  $output .= '</SUBJECTS>
</SEARCH_RESULT>
</SSR_GET_CLASSES_RESP>';

  print $output;
}

/**
 * A detailed class listing
 */
function cu_class_primer_detail($arg2, $arg3, $arg4, $arg5) {
  drupal_add_http_header('Content-Type', 'text/xml');
  //$inst = 'CUBLD';
  //$term = '2164';
  //$subject = 'HIST';

  $inst = $arg2;
  $term = $arg3;
  $subject = $arg4;
  $course_id = $arg5;
  $count = 0;

  $output = '<?xml version="1.0" encoding="UTF-8"?>
<SSR_GET_CLASSES_RESP xmlns:ser="http://xmlns.oracle.com/Enterprise/HCM/services">
    <SEARCH_RESULT>
    <ERROR_WARN_TEXT/>
    <SSR_COURSE_COUNT>1</SSR_COURSE_COUNT>
    <SSR_ERR_LMT_EXCEED/>
    <SSR_WRN_LMT_EXCEED/>
    <SSR_CLASS_COUNT>1</SSR_CLASS_COUNT>
    <SUBJECTS>';

  $results = db_query('SELECT * FROM {class_search} WHERE CRSE_CD = :course_id', array(':course_id' => $course_id));

  foreach ($results as $class) {
    //dsm($class);
    $count++;
//mimic XML structure from master response
//dsm($course);
    $title = check_plain($class->CRSE_TTL_LD);
    $output .= '
    <SUBJECT index="' . $count . '">
      <CRSE_ID>' . $course_id  . '</CRSE_ID>
      <CRSE_ID_LOVDescr>' . $title  . '</CRSE_ID_LOVDescr>
      <SUBJECT>' . $subject  . '</SUBJECT>
      <SUBJECT_LOVDescr>' . $class->SBJCT_LD  . '</SUBJECT_LOVDescr>
      <CATALOG_NBR>' . $class->CATALOG_NBR  . '</CATALOG_NBR>
      <INSTITUTION>' . $inst  . '</INSTITUTION>
      <INSTITUTION_LOVDescr>CU Boulder</INSTITUTION_LOVDescr>
      <ACAD_CAREER>UGRD</ACAD_CAREER>
      <ACAD_CAREER_LOVDescr>Undergraduate</ACAD_CAREER_LOVDescr>
      <COURSE_TITLE_LONG>' . $title  . '</COURSE_TITLE_LONG>
      <CRSE_OFFER_NBR>1</CRSE_OFFER_NBR>
      <CLASSES_SUMMARY>
        <CLASS_SUMMARY index="1">
          <CRSE_ID>' . $course_id  . '</CRSE_ID>
          <CRSE_ID_LOVDescr>' . $title  . '</CRSE_ID_LOVDescr>
          <SUBJECT>' . $subject  . '</SUBJECT>
          <SUBJECT_LOVDescr>' . $class->SBJCT_LD . '</SUBJECT_LOVDescr>
          <CATALOG_NBR>' . $class->CATALOG_NBR . '</CATALOG_NBR>
          <CRSE_OFFER_NBR>1</CRSE_OFFER_NBR>
          <STRM>' . $term  . '</STRM>
          <STRM_LOVDescr>Spring 2016</STRM_LOVDescr>
          <SESSION_CODE>BL3</SESSION_CODE>
          <SESSION_CODE_LOVDescr>CE Online TermBased Full Sess</SESSION_CODE_LOVDescr>
          <CLASS_SECTION>581</CLASS_SECTION>
          <CLASS_NBR>36370</CLASS_NBR>
          <SCHEDULE_PRINT>Y</SCHEDULE_PRINT>
          <SCHEDULE_PRINT_LOVDescr>Yes</SCHEDULE_PRINT_LOVDescr>
          <COMBINED_SECTION/>
          <COMBINED_SECTION_LOVDescr/>
          <STATUS>O</STATUS>
          <CLASS_TOPIC>0</CLASS_TOPIC>
          <SSR_CLASSNAME_LONG/>
          <STATUS>O</STATUS>
          <STATUS_LOVDescr>Open</STATUS_LOVDescr>
          <SSR_COMPONENT>LEC</SSR_COMPONENT>
          <SSR_COMPONENT_LOVDescr>Lecture</SSR_COMPONENT_LOVDescr>
          <CAMPUS>CEPS</CAMPUS>
          <CAMPUS_LOVDescr>Boulder Continuing Education</CAMPUS_LOVDescr>
          <INSTITUTION>CUBLD</INSTITUTION>
          <SSR_DESCRLONG>
            Detailed consideration of human biology, the place of humans in the animal kingdom, primate ecology, and fossil evidence for human evolution. Credit not granted for this course and ANTH 2050. Required for ANTH majors. Approved for GT-SC1. Meets MAPS requirement for natural science: non-lab. Approved for arts and sciences core curriculum: natural science.
          </SSR_DESCRLONG>
          <INSTRUCTION_MODE>OL</INSTRUCTION_MODE>
          <INSTRUCTION_MODE_LOVDescr>Online</INSTRUCTION_MODE_LOVDescr>
          <ENRL_CAP>35</ENRL_CAP>
          <ENRL_TOT>19</ENRL_TOT>
          <WAIT_CAP>999</WAIT_CAP>
          <WAIT_TOT>0</WAIT_TOT>
          <ENRL_STAT>O</ENRL_STAT>
          <CLASS_NOTES>
            <CLASS_NOTE></CLASS_NOTE>
          </CLASS_NOTES>
          <UNITS_MAX>3 3 3 3 3 3 3 3</UNITS_MAX>
          <UNITS_MIN>3 3 3 3 3 3 3 3</UNITS_MIN>
          <CRSE_ATTR>BCRQ BCRQ BCRQ BCRQ BCRQ BCRQ GT GT</CRSE_ATTR>
          <CRSE_ATTR_VALUE>AM AM AX AX AY AY GT-SC1 GT-SC1</CRSE_ATTR_VALUE>
          <UNITS_ACAD_PROG>3 3 3 3 3 3 3 3</UNITS_ACAD_PROG>
          <RQRMNT_GROUP></RQRMNT_GROUP>
          <RQRMNT_GROUP_DESCR></RQRMNT_GROUP_DESCR>
          <CRS_TOPIC_ID>0</CRS_TOPIC_ID>
          <CRS_TOPIC_DESCR/>
          <CLASSES_MEETING_PATTERNS>
            <CLASS_MEETING_PATTERN>
              <MEETING_TIME_START>.</MEETING_TIME_START>
              <MEETING_TIME_END>.</MEETING_TIME_END>
              <MON>N</MON>
              <TUES>N</TUES>
              <WED>N</WED>
              <THURS>N</THURS>
              <FRI>N</FRI>
              <SAT>N</SAT>
              <SUN>N</SUN>
              <START_DT>2016-01-19</START_DT>
              <END_DT>2016-04-29</END_DT>
              <CRS_TOPIC_ID>0</CRS_TOPIC_ID>
              <CRS_TOPIC_ID_LOVDescr/>
              <SCC_LATITUDE>0</SCC_LATITUDE>
              <SCC_LONGITUDE>0</SCC_LONGITUDE>
              <SSR_MTG_SCHED_LONG>TBA</SSR_MTG_SCHED_LONG>
              <SSR_MTG_LOC_LONG>Continuing Ed Online Class</SSR_MTG_LOC_LONG>
              <SSR_INSTR_LONG>Jonathan O Brien</SSR_INSTR_LONG>
              <SSR_MTG_DT_LONG>2016-01-19 - 2016-04-29</SSR_MTG_DT_LONG>
              <SSR_TOPIC_LONG>TBA</SSR_TOPIC_LONG>
              <CLASS_INSTRUCTORS>
                <CLASS_INSTRUCTOR>
                  <EMPLID>810288959</EMPLID>
                  <INSTR_ROLE>PI</INSTR_ROLE>
                  <INSTR_ROLE_LOVDescr>Primary Instructor</INSTR_ROLE_LOVDescr>
                  <NAME_DISPLAY>Jonathan O Brien</NAME_DISPLAY>
                  <LAST_NAME>O Brien</LAST_NAME>
                  <FIRST_NAME>Jonathan</FIRST_NAME>
                  <ENCRYPTED_EMPLID>S80Iqv7Cd2HvU4X6XIMm0Q==</ENCRYPTED_EMPLID>
                </CLASS_INSTRUCTOR>
              </CLASS_INSTRUCTORS>
            </CLASS_MEETING_PATTERN>
          </CLASSES_MEETING_PATTERNS>
        </CLASS_SUMMARY>
      </CLASSES_SUMMARY>
    </SUBJECT>';
  }

  $output .= '</SUBJECTS>
</SEARCH_RESULT>
</SSR_GET_CLASSES_RESP>';

  print $output;
}

/**
 * A detailed class listing
 */
function cu_classes_primer_detail($arg2, $arg3, $arg4, $arg5) {
  drupal_add_http_header('Content-Type', 'text/xml');
  //$inst = 'CUBLD';
  //$term = '2164';
  //$subject = 'HIST';

  $inst = $arg2;
  $term = $arg3;
  $subject = $arg4;
  $course_id = $arg5;
  $count = 0;

  $output = '<?xml version="1.0" encoding="UTF-8"?>
<SSR_GET_CLASSES_RESP xmlns:ser="http://xmlns.oracle.com/Enterprise/HCM/services">
    <SEARCH_RESULT>
    <SUBJECTS>';

  $results = db_query('SELECT * FROM {class_search} WHERE CRSE_CD = :course_id', array(':course_id' => $course_id));

  foreach ($results as $class) {

    $count++;

    $title = check_plain($class->CRSE_TTL_LD);
    $output .= '
    <SUBJECT index="' . $count . '">
      <CRSE_ID>' . $course_id  . '</CRSE_ID>
      <CRSE_ID_LOVDescr>' . $title  . '</CRSE_ID_LOVDescr>
      <SUBJECT>' . $subject  . '</SUBJECT>
      <SUBJECT_LOVDescr>' . $class->SBJCT_LD  . '</SUBJECT_LOVDescr>
      <CATALOG_NBR>' . $class->CATALOG_NBR  . '</CATALOG_NBR>
      <INSTITUTION>' . $inst  . '</INSTITUTION>
      <INSTITUTION_LOVDescr>CU Boulder</INSTITUTION_LOVDescr>
      <ACAD_CAREER>UGRD</ACAD_CAREER>
      <ACAD_CAREER_LOVDescr>Undergraduate</ACAD_CAREER_LOVDescr>
      <COURSE_TITLE_LONG>' . $title  . '</COURSE_TITLE_LONG>
      <CRSE_OFFER_NBR>1</CRSE_OFFER_NBR>

    </SUBJECT>';
  }

  $output .= '</SUBJECTS>
</SEARCH_RESULT>
</SSR_GET_CLASSES_RESP>';

  print $output;
}



