<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function cu_class_primer_bundle_menu() {
  $items['admin/config/system/class-primer'] = array(
    'title' => 'Class Primer',
    'description' =>  'Import classes.',
    'page callback' => 'cu_class_primer_import',
    'access arguments' => array('administer modules'),
  );

  $items['primer/courses'] = array(
    'title' => 'Class Primer - Master XML',
    'description' =>  'Import classes.',
    'page callback' => 'cu_class_primer_master',
    'access callback' => 'cu_class_primer_access',
    'type' => MENU_CALLBACK,
  );

  $items['primer/class'] = array(
    'title' => 'Class Primer - Detail XML',
    'description' =>  'Import classes.',
    'page callback' => 'cu_class_primer_detail',
    'access callback' => 'cu_class_primer_access',
    'type' => MENU_CALLBACK,
  );

  $items['primer/classes/test'] = array(
    'title' => 'Class Primer - Detail XML',
    'description' =>  'Import classes.',
    'page callback' => 'cu_classes_primer_detail',
    'access callback' => 'cu_class_primer_access',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Access callback for ??
 */
function cu_class_primer_access() {
  // switch to a custom permission?
  return TRUE;
}

/**
 * A basic course listing
 */
function cu_class_primer_master($arg2, $arg3, $arg4) {
  drupal_add_http_header('Content-Type', 'text/xml');
  //$inst = 'CUBLD';
  //$term = '2164';
  //$subject = 'HIST';

  $inst = $arg2;
  $term = $arg3;
  $subject = $arg4;

  $output = '<?xml version="1.0" encoding="UTF-8"?>
  <SSR_GET_CLASSES_RESP xmlns="http://xmlns.oracle.com/Enterprise/HCM/services">
    <SEARCH_RESULT>
      <SUBJECTS>';
  //$results = db_query('SELECT * FROM {class_search} WHERE SBJCT_CD = :subject', array(':subject' => $subject));
  $results = db_query('SELECT DISTINCT(CRSE_ID), SUBJECT, CATALOG_NBR, ACAD_CAR_CD, COURSE_TITLE_LONG FROM {class_psquery} WHERE SUBJECT = :subject', array(':subject' => $subject));


  foreach ($results as $course) {
    //mimic XML structure from master response
    //dsm($course);
    $title = check_plain($course->COURSE_TITLE_LONG);
    $output .= "
    <SUBJECT>
      <CRSE_ID>$course->CRSE_ID</CRSE_ID>
      <SUBJECT>$course->SUBJECT</SUBJECT>
      <CATALOG_NBR>$course->CATALOG_NBR</CATALOG_NBR>
      <ACAD_CAREER>$course->ACAD_CAR_CD</ACAD_CAREER>
      <COURSE_TITLE_LONG>$title</COURSE_TITLE_LONG>
      <CRSE_OFFER_NBR>1</CRSE_OFFER_NBR>
    </SUBJECT>";
  }

  $output .= '</SUBJECTS>
</SEARCH_RESULT>
</SSR_GET_CLASSES_RESP>';

  print $output;
}
/**
 * A detailed class listing
 */
function cu_classes_primer_detail() {
  drupal_add_http_header('Content-Type', 'text/xml');

  $output = '<?xml version="1.0" encoding="UTF-8"?>
<SSR_GET_CLASSES_RESP xmlns="http://xmlns.oracle.com/Enterprise/HCM/services">
  <SEARCH_RESULT>
    <SUBJECTS>
      <SUBJECT>
        <CRSE_ID>123</CRSE_ID>
        <SUBJECT>test</SUBJECT>
        <CATALOG_NBR>123</CATALOG_NBR>
        <ACAD_CAREER>UNGR</ACAD_CAREER>
        <COURSE_TITLE_LONG>testing</COURSE_TITLE_LONG>
        <CRSE_OFFER_NBR>1</CRSE_OFFER_NBR>
      </SUBJECT>
    </SUBJECTS>
  </SEARCH_RESULT>
</SSR_GET_CLASSES_RESP>';

  print $output;
}

/**
 * A detailed class listing
 */
function cu_class_primer_detail($arg2, $arg3, $arg4, $arg5) {
  drupal_add_http_header('Content-Type', 'text/xml');
  //$inst = 'CUBLD';
  //$term = '2164';
  //$subject = 'HIST';

  $inst = $arg2;
  $term = $arg3;
  $subject_cd = $arg4;
  $course_id = $arg5;
  $subject_count = 0;
  $class_count = 0;

  $output = '<?xml version="1.0" encoding="UTF-8"?>
<ser:SSR_GET_CLASSES_RESP xmlns:ser="http://xmlns.oracle.com/Enterprise/HCM/services">
    <ser:SEARCH_RESULT>
    <ser:ERROR_WARN_TEXT/>
    <ser:SSR_COURSE_COUNT>1</ser:SSR_COURSE_COUNT>
    <ser:SSR_ERR_LMT_EXCEED/>
    <ser:SSR_WRN_LMT_EXCEED/>
    <ser:SSR_CLASS_COUNT>1</ser:SSR_CLASS_COUNT>
    <ser:SUBJECTS>';

  //$results = db_query('SELECT * FROM {class_search} WHERE CRSE_CD = :course_id', array(':course_id' => $course_id));
  $results = db_query('SELECT DISTINCT(CRSE_ID), COURSE_TITLE_LONG, SUBJECT, CATALOG_NBR, ACAD_CAR_CD FROM {class_psquery} WHERE CRSE_ID = :course_id', array(':course_id' => $course_id));
  foreach ($results as $subject) {
    //dsm($subject);
    $subject_count++;
    //mimic XML structure from detail response

    $title = check_plain($subject->COURSE_TITLE_LONG);
    //$subject_nbr = str_replace( ',', '', $subject->CLASS_NUM);

    $output .= '<ser:SUBJECT index="' . $subject_count . '">
      <ser:CRSE_ID>' . $course_id  . '</ser:CRSE_ID>
      <ser:CRSE_ID_LOVDescr>' . $title  . '</ser:CRSE_ID_LOVDescr>
      <ser:SUBJECT>' . $subject_cd  . '</ser:SUBJECT>
      <ser:SUBJECT_LOVDescr>' . $subject->SUBJECT  . '</ser:SUBJECT_LOVDescr>
      <ser:CATALOG_NBR>' . $subject->CATALOG_NBR  . '</ser:CATALOG_NBR>
      <ser:INSTITUTION>' . $inst  . '</ser:INSTITUTION>
      <ser:INSTITUTION_LOVDescr>CU Boulder</ser:INSTITUTION_LOVDescr>
      <ser:ACAD_CAREER>' . $subject->ACAD_CAR_CD  . '</ser:ACAD_CAREER>
      <ser:ACAD_CAREER_LOVDescr></ser:ACAD_CAREER_LOVDescr>
      <ser:COURSE_TITLE_LONG>' . $title  . '</ser:COURSE_TITLE_LONG>
      <ser:CRSE_OFFER_NBR>1</ser:CRSE_OFFER_NBR>
      <ser:CLASSES_SUMMARY>';

    // class meeting
    //$classes = db_query('SELECT * FROM {class_psquery} WHERE CRSE_ID = :course_id', array(':course_id' => $course_id));

    //GROUP_CONCAT(CRSE_ATTR_VALUE_CD SEPARATOR ', ') AS CRSE_ATTR_VALUE_CD

    $classes = db_query("SELECT CLASS_NBR, SUBJECT, CLASS_SECTION, SESSION_CD, CATALOG_NBR,
    ACAD_CAR_CD, CRSE_LD, COURSE_TITLE_LONG, CLASS_NBR, CLASS_TYPE, SSR_DESCRLONG,
    INSTRUCTION_MODE, START_DT, END_DT, MEETING_TIME_START,
    MEETING_TIME_END, Mon, Tues, Wed, Thurs, Fri, Sat, Sun, SSR_MTG_LOC_LONG,
    SSR_INSTR_LONG,INSTITUTION, ENRL_STAT, ENRL_CAP, ENRL_TOT, WAIT_TOT, CRSE_ID,
    CRSE_ATTR_CD, MinUnits, MaxUnits, CRSE_ATTR_VALUE_CD
    FROM class_psquery WHERE CRSE_ID = :course_id", array(':course_id' => $course_id));

    foreach ($classes as $class) {
      $class_count++;
      //clean up times from csv imports tables
      //1/1/1900 9:00:00.000000 AM
      $time_start = str_replace(":00.000000", "", $class->MEETING_TIME_START);
      $time_start = str_replace("1/1/1900 ", "", $time_start);
      //dsm($time_start);

      $time_end = str_replace(":00.000000", "", $class->MEETING_TIME_START);
      $time_end = str_replace("1/1/1900 ", "", $time_end);
      //dsm($time_end);

      // build meeting schedule long
      $schedule = '';
      if ($class->Mon == 'Y') {
        $schedule .= 'M';
      }
      if ($class->Tues == 'Y') {
        $schedule .= 'Tu';
      }
      if ($class->Wed == 'Y') {
        $schedule .= 'W';
      }
      if ($class->Thurs == 'Y') {
        $schedule .= 'Th';
      }
      if ($class->Fri == 'Y') {
        $schedule .= 'F';
      }
      if ($class->Sat == 'Y') {
        $schedule .= 'Sa';
      }
      if ($class->Sun == 'Y') {
        $schedule .= 'Su';
      }

      $schedule .= ' ' . $class->MEETING_TIME_START . ' - ' . $class->MEETING_TIME_END;


      $output .= '      <ser:CLASS_SUMMARY index="' . $class_count. '">
          <ser:CRSE_ID>' . $course_id . '</ser:CRSE_ID>
          <ser:CRSE_ID_LOVDescr>' . $title . '</ser:CRSE_ID_LOVDescr>
          <ser:SUBJECT>' . $subject_cd . '</ser:SUBJECT>
          <ser:SUBJECT_LOVDescr>' . $class->SUBJECT . '</ser:SUBJECT_LOVDescr>
          <ser:CATALOG_NBR>' . $class->CATALOG_NBR . '</ser:CATALOG_NBR>
          <ser:CRSE_OFFER_NBR>1</ser:CRSE_OFFER_NBR>
          <ser:STRM>' . $term . '</ser:STRM>
          <ser:STRM_LOVDescr>' . $subject->TEM_LD . '</ser:STRM_LOVDescr>
          <ser:SESSION_CODE>' . $class->SESSION_CD . '</ser:SESSION_CODE>
          <ser:SESSION_CODE_LOVDescr></ser:SESSION_CODE_LOVDescr>
          <ser:CLASS_SECTION>' . $class->CLASS_SECTION . '</ser:CLASS_SECTION>
          <ser:CLASS_NBR>' . $class->CLASS_NBR . '</ser:CLASS_NBR>
          <ser:SCHEDULE_PRINT>Y</ser:SCHEDULE_PRINT>
          <ser:SCHEDULE_PRINT_LOVDescr>Yes</ser:SCHEDULE_PRINT_LOVDescr>
          <ser:COMBINED_SECTION/>
          <ser:COMBINED_SECTION_LOVDescr/>
          <ser:STATUS>O</ser:STATUS>
          <ser:CLASS_TOPIC>0</ser:CLASS_TOPIC>
          <ser:SSR_CLASSNAME_LONG/>
          <ser:STATUS>O</ser:STATUS>
          <ser:STATUS_LOVDescr>Open</ser:STATUS_LOVDescr>
          <ser:SSR_COMPONENT>' . $class->CLASS_SECTION . '</ser:SSR_COMPONENT>
          <ser:SSR_COMPONENT_LOVDescr></ser:SSR_COMPONENT_LOVDescr>
          <ser:CAMPUS></ser:CAMPUS>
          <ser:CAMPUS_LOVDescr></ser:CAMPUS_LOVDescr>
          <ser:INSTITUTION>CUBLD</ser:INSTITUTION>
          <ser:SSR_DESCRLONG>' . $class->SSR_DESCRLONG . '</ser:SSR_DESCRLONG>
          <ser:INSTRUCTION_MODE>' . $class->INSTRUCTION_MODE . '</ser:INSTRUCTION_MODE>
          <ser:INSTRUCTION_MODE_LOVDescr></ser:INSTRUCTION_MODE_LOVDescr>
          <ser:ENRL_CAP>' . $class->ENRL_CAP . '</ser:ENRL_CAP>
          <ser:ENRL_TOT>' . $class->ENRL_TOT . '</ser:ENRL_TOT>
          <ser:WAIT_CAP>' . $class->ENRL_CAP . '</ser:WAIT_CAP>
          <ser:WAIT_TOT>' . $class->WAIT_TOT . '</ser:WAIT_TOT>
          <ser:ENRL_STAT>' . $class->ENRL_STAT . '</ser:ENRL_STAT>
          <ser:CLASS_NOTES>
            <ser:CLASS_NOTE></ser:CLASS_NOTE>
          </ser:CLASS_NOTES>
          <ser:UNITS_MAX>' . $class->MinUnits . '</ser:UNITS_MAX>
          <ser:UNITS_MIN>' . $class->MaxUnits . '</ser:UNITS_MIN>
          <ser:CRSE_ATTR>' . $class->CRSE_ATTR_CD . '</ser:CRSE_ATTR>
          <ser:CRSE_ATTR_VALUE>' . $class->CRSE_ATTR_VALUE_CD . '</ser:CRSE_ATTR_VALUE>
          <ser:UNITS_ACAD_PROG>' . $class->MaxUnits . '</ser:UNITS_ACAD_PROG>
          <ser:RQRMNT_GROUP></ser:RQRMNT_GROUP>
          <ser:RQRMNT_GROUP_DESCR></ser:RQRMNT_GROUP_DESCR>
          <ser:CRS_TOPIC_ID>0</ser:CRS_TOPIC_ID>
          <ser:CRS_TOPIC_DESCR/>
          <ser:CLASSES_MEETING_PATTERNS>
            <ser:CLASS_MEETING_PATTERN>
              <ser:MEETING_TIME_START>' . $class->MEETING_TIME_START . '</ser:MEETING_TIME_START>
              <ser:MEETING_TIME_END>' . $class->MEETING_TIME_END . '</ser:MEETING_TIME_END>
              <ser:MON>' . $class->Mon . '</ser:MON>
              <ser:TUES>' . $class->Tues . '</ser:TUES>
              <ser:WED>' . $class->Wed . '</ser:WED>
              <ser:THURS>' . $class->Thurs . '</ser:THURS>
              <ser:FRI>' . $class->Fri . '</ser:FRI>
              <ser:SAT>' . $class->Sat . '</ser:SAT>
              <ser:SUN>' . $class->Sun . '</ser:SUN>
              <ser:START_DT>' . $class->START_DT . '</ser:START_DT>
              <ser:END_DT>' . $class->END_DT . '</ser:END_DT>
              <ser:CRS_TOPIC_ID>0</ser:CRS_TOPIC_ID>
              <ser:CRS_TOPIC_ID_LOVDescr/>
              <ser:SCC_LATITUDE>0</ser:SCC_LATITUDE>
              <ser:SCC_LONGITUDE>0</ser:SCC_LONGITUDE>
              <ser:SSR_MTG_SCHED_LONG>' . $schedule . '</ser:SSR_MTG_SCHED_LONG>
              <ser:SSR_MTG_LOC_LONG>' . $class->SSR_MTG_LOC_LONG . '</ser:SSR_MTG_LOC_LONG>
              <ser:SSR_INSTR_LONG>' . $class->SSR_INSTR_LONG . '</ser:SSR_INSTR_LONG>
              <ser:SSR_MTG_DT_LONG>2016-01-19 - 2016-04-29</ser:SSR_MTG_DT_LONG>
              <ser:SSR_TOPIC_LONG>TBA</ser:SSR_TOPIC_LONG>
              <ser:CLASS_INSTRUCTORS>
                <ser:CLASS_INSTRUCTOR>
                  <ser:EMPLID></ser:EMPLID>
                  <ser:INSTR_ROLE>PI</ser:INSTR_ROLE>
                  <ser:INSTR_ROLE_LOVDescr>Primary Instructor</ser:INSTR_ROLE_LOVDescr>
                  <ser:NAME_DISPLAY>' . $class->SSR_INSTR_LONG . '</ser:NAME_DISPLAY>
                  <ser:LAST_NAME></ser:LAST_NAME>
                  <ser:FIRST_NAME></ser:FIRST_NAME>
                  <ser:ENCRYPTED_EMPLID></ser:ENCRYPTED_EMPLID>
                </ser:CLASS_INSTRUCTOR>
              </ser:CLASS_INSTRUCTORS>
            </ser:CLASS_MEETING_PATTERN>
          </ser:CLASSES_MEETING_PATTERNS>
        </ser:CLASS_SUMMARY>';
    }
    $output .= '    </ser:CLASSES_SUMMARY>
    </ser:SUBJECT>';
  }

  $output .= '</ser:SUBJECTS>
</ser:SEARCH_RESULT>
</ser:SSR_GET_CLASSES_RESP>
';

  //if for some reason we don't find any classes for this course, return nothing
  if ($class_count == 0) {
    print '';
  }
  print $output;
}
